language: java
jdk:
  - oraclejdk7

# need to override travis 'install' since it will try gpg sign and fail.
#install: mvn clean package -DskipTests=true
install: echo "Maven build controlled by the script command."

# standard maven build.
script: mvn clean verify

# coveralls.io integration of cobertura code coverage data.
after_success:
  - mvn cobertura:cobertura coveralls:report

branches:
  only:
    - master
